In [1]:
import torch

In [16]:
a=torch.rand(4,4)

TypeError: rand() received an invalid combination of arguments - got (float, float, int, int), but expected one of:
 * (tuple of ints size, *, torch.Generator generator, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


In [15]:
print(a)

tensor([[0.8284, 0.3895, 0.6962, 0.2380],
        [0.1487, 0.3079, 0.1153, 0.3945],
        [0.8404, 0.4523, 0.9318, 0.7919],
        [0.1431, 0.7065, 0.4428, 0.7614]])


In [10]:
diff = torch.roll(a,1,0)-a

In [11]:
print(diff)

tensor([[-1.7833, -2.4091, -1.5977, -0.1998],
        [ 0.7118,  1.4512, -0.6345,  0.1150],
        [ 0.9839, -0.6674,  3.1784,  0.4125],
        [ 0.0876,  1.6253, -0.9463, -0.3277]])


In [12]:
import numpy as np
f=np.random.uniform(-np.pi, np.pi)

In [24]:
4 + torch.rand(2,2)

tensor([[4.3353, 4.0498],
        [4.4844, 4.5959]])

In [36]:
torch.rand(1)

tensor([0.3826])